name: marklogic_spark_getting_started

services:

  marklogic:
    image: "marklogicdb/marklogic-db:latest-11"
    platform: linux/amd64
    cap_drop:
      - NET_RAW
    environment:
      - MARKLOGIC_INIT=true
      - MARKLOGIC_ADMIN_USERNAME=admin
      - MARKLOGIC_ADMIN_PASSWORD=admin
    volumes:
      - ./docker/marklogic/logs:/var/opt/MarkLogic/Logs
    ports:
      - 8000-8003:8000-8003
