name: docker-tests-marklogic-spark

services:

  # See https://caddyserver.com/docs/quick-starts/reverse-proxy for more information on using Caddy as a reverse proxy
  # and load balancer.
  caddy-load-balancer:
    image: caddy:2-alpine
    volumes:
      # Not mapping the Caddy data directory, as that causes issues for Jenkins.
      - ./docker/caddy/config/Caddyfile:/etc/caddy/Caddyfile
    ports:
      # Expand this range as needed. See Caddyfile for which ports are used for reverse proxies.
      - "8115:8115"
      - "8116:8116"

  marklogic:
    image: "${MARKLOGIC_IMAGE}"
    platform: linux/amd64
    environment:
      - MARKLOGIC_INIT=true
      - MARKLOGIC_ADMIN_USERNAME=admin
      - MARKLOGIC_ADMIN_PASSWORD=admin
    volumes:
      - ${MARKLOGIC_LOGS_VOLUME}:/var/opt/MarkLogic/Logs
    ports:
      - "8000-8002:8000-8002"
      - "8015:8015"
      - "8016:8016"
