langchain4j.azure-open-ai.embedding-model.api-key=${AZURE_API_KEY}
langchain4j.azure-open-ai.embedding-model.deployment-name=text-test-embedding-ada-002
langchain4j.azure-open-ai.embedding-model.endpoint=https://gpt-testing-custom-data1.openai.azure.com
